theme: jekyll-theme-minimal
title: The World Atlas of Last Interglacial Shorelines
logo: /img/walis_logo.png
description: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5979520.svg)](https://doi.org/10.5281/zenodo.5979520)
show_downloads: true
